default:
  tags:
    - k8s

stages:
  - build
  - run

build-job:
  stage: build
  allow_failure: true
  image:
    name: moby/buildkit:latest
    entrypoint: [""]
  variables:
    GIT_FETCH_EXTRA_FLAGS: none
    GIT_STRATEGY: "clone"
    IMAGE_NAME: "database-manager"
    IMAGE_VERSION: ""
  before_script:
    - apk add --no-cache jq moreutils
  script:
    - /bin/sh build.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

run_script:postgresql:
  stage: run
  allow_failure: true
  image: $CI_REGISTRY_IMAGE/database-manager:latest
  variables:
    ACTION: ""
    SWAP: ""
    VERBOSE: ""
  script:
    - cd app
    - |
      echo "[backup]" > psql.config
      echo "host=$BACKUP_HOST" >> psql.config
      echo "port=$BACKUP_PORT" >> psql.config
      echo "user=$BACKUP_USER" >> psql.config
      echo "password=$BACKUP_PASSWORD" >> psql.config
      echo "db=$BACKUP_DB" >> psql.config
    - |
      echo "[restore]" >> psql.config
      echo "host=$RESTORE_HOST" >> psql.config
      echo "port=$RESTORE_PORT" >> psql.config
      echo "user=$RESTORE_USER" >> psql.config
      echo "password=$RESTORE_PASSWORD" >> psql.config
      echo "user_new=$RESTORE_USER_NEW" >> psql.config
      echo "password_new=$RESTORE_PASSWORD_NEW" >> psql.config
      echo "db_new=$RESTORE_DB_NEW" >> psql.config
    - python postgres-database-manager.py --configfile=psql.config --action=$ACTION ${SWAP:+--swap} ${VERBOSE:+--verbose}
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $JOB_NAME == "run_script:postgresql"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: manual

run_script:mysql:
  stage: run
  allow_failure: true
  image: $CI_REGISTRY_IMAGE/database-manager:latest
  variables:
    ACTION: ""
    SWAP: ""
    VERBOSE: ""
  script:
    - cd app
    - |
      echo "[backup]" > mysql.config
      echo "host=$BACKUP_HOST" >> mysql.config
      echo "port=$BACKUP_PORT" >> mysql.config
      echo "user=$BACKUP_USER" >> mysql.config
      echo "password=$BACKUP_PASSWORD" >> mysql.config
      echo "db=$BACKUP_DB" >> mysql.config
    - |
      echo "[restore]" >> mysql.config
      echo "host=$RESTORE_HOST" >> mysql.config
      echo "port=$RESTORE_PORT" >> mysql.config
      echo "user=$RESTORE_USER" >> mysql.config
      echo "password=$RESTORE_PASSWORD" >> mysql.config
      echo "user_new=$RESTORE_USER_NEW" >> mysql.config
      echo "password_new=$RESTORE_PASSWORD_NEW" >> mysql.config
      echo "db_new=$RESTORE_DB_NEW" >> mysql.config
    - python mysql-database-manager.py --configfile=mysql.config --action=$ACTION ${SWAP:+--swap} ${VERBOSE:+--verbose}
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $JOB_NAME == "run_script:mysql"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: manual
