version: "3.9"

services:

  app:
    build: .
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    networks:
      - database-manager-net

networks:
  database-manager-net:
    driver: bridge
    name: bridge-database-manager
    ipam:
      config:
        - subnet: 172.34.0.0/16
